#!/bin/bash

#PBS -N d2q9-bgk
#PBS -joe
#PBS -o d2q9-bgk.out
#PBS -q teaching
#PBS -l epilogue=~ggdagw/epilogue.sh
#PBS -l nodes=1:ppn=1,walltime=00:15:00

#! Mail to user if job aborts
#PBS -m a

#! application name
application="./d2q9-bgk"

#! Run options for the application
options="input_256x256.params obstacles_256x256.dat"

#!export TAU_METRICS=TIME,PAPI_FP_INS,PAPI_L1_DCM
#!export TAU_SAMPLING=1

###############################################################
### You should not have to change anything below this line ####
###############################################################

#! change the working directory (default is home directory)

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID
echo This jobs runs on the following machines:
echo `cat $PBS_NODEFILE | uniq`

numcores=`wc $PBS_NODEFILE | awk '{ print $1 }'`

#! Create a machine file for MPI
cat $PBS_NODEFILE > machine.file.$PBS_JOBID

#!export OMP_NUM_THREADS=$numcores
#!export OMP_PROC_BIND=TRUE
#!export OMP_WAIT_POLICY=ACTIVE

#! Run the executable
#!$application $options
mpirun -np $numcores -machinefile machine.file.$PBS_JOBID $application $options
