#!/bin/bash

#PBS -N scaling1024x1024
#PBS -joe
#PBS -o scaling1024x1024.out
#PBS -q teaching
#PBS -l epilogue=~ggdagw/epilogue.sh
#PBS -l nodes=4:ppn=16,walltime=03:00:00

#! Mail to user if job aborts
#PBS -m a

#! application name
application="./d2q9-bgk"

#! Run options for the application
options="input_1024x1024.params obstacles_1024x1024.dat"

numthreads=1
numranks=64

#!module add intel-cluster-studio/compiler/64/13.1/117
#!module add intel-mpi/64/4.1.0/024
module load languages/intel-compiler-16-u2
#!module unload languages/gcc-4.8.4
#!source /cm/shared/languages/Intel-Compiler-XE-16-U2/itac/9.1.2.024/bin/itacvars.sh
#!source /cm/shared/languages/Intel-Compiler-XE-16-U2/impi/5.1.3.181/intel64/bin/mpivars.sh

###############################################################
### You should not have to change anything below this line ####
###############################################################

#! change the working directory (default is home directory)

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID
echo This jobs runs on the following machines:
echo `cat $PBS_NODEFILE | uniq`

numcores=`wc $PBS_NODEFILE | awk '{ print $1 }'`

#! Create a machine file for MPI
cat $PBS_NODEFILE > machine.file.$PBS_JOBID
cat $PBS_NODEFILE | uniq > host.file.$PBS_JOBID

#!export OMP_NUM_THREADS=$numthreads
#!export OMP_PROC_BIND=TRUE
#!export OMP_WAIT_POLICY=ACTIVE

#!export I_MPI_DEBUG=5
export I_MPI_ASYNC_PROGRESS=1
#!export I_MPI_ASYNC_PROGRESS_PIN=yes
export I_MPI_PIN_DOMAIN=core
export I_MPI_PIN_ORDER=compact
#!export I_MPI_STATS=all

# !Run the executable
#!$application $options

for i in `seq 1 64`;
do
  echo $i
  mpirun -np $i -hostfile host.file.$PBS_JOBID $application $options
done
